### ISSUE TITLE
Compiler Status

### ISSUE THREAD

**Issue by tedbauer** [tedbauer/tigger#1]
- [X] Lexical Analysis
- [X] Parsing
- [x] Abstract Syntax
- [ ] Semantic Analysis
- [ ] Activation Records
- [ ] Translation to IR
- [ ] Basic Blocks and Traces
- [ ] Instruction Selection
- [ ] Liveness Analysis
- [ ] Register Allocation
- [ ] Garbage Collection
- [ ] Object-Oriented Stuff
- [ ] Functional Stuff
- [ ] Polymorphic Types
- [ ] Dataflow Analysis
- [ ] Loop Optimizations
- [ ] Static Single-Assignment Form
- [ ] Pipelining and Scheduling
- [ ] Memory Hierarchy Stuff
